export const primaryColor = '#012030'
export const secondaryColor = '#13678A'
export const tertiaryColor = '#45C4B0'
export const whiteColor  = '#FFFFFF'
export const greyColor = '#ADA7A7'
export const redColor = '#FF0000'
